[package]
name = "carapace"
version = "0.1.0"
authors = ["Morten Kristensen <msk@nullpointer.dk>"]
edition = "2018"

[dependencies]
dirs = "1.0.4"
term = "0.5.1"
rustyline = "2.1.0"
json = "0.11.13"
regex = "1.1.0"
lazy_static = "1.2.0"
clap = "2.32.0"
glob = "0.2.11"