[package]
name = "carapace"
version = "0.1.2"
authors = ["Morten Kristensen <me@mortens.dev>"]
edition = "2018"

[dependencies]
dirs = "2.0.2"
termcolor = "1.1.0"
rustyline = "5.0.6"
json = "0.12.1"
regex = "1.3.3"
lazy_static = "1.4.0"
clap = "2.33.0"
glob = "0.3.0"
libc = "0.2.66"
is_executable = "0.1.2"
